# Generated by Django 4.1.4 on 2022-12-21 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_caps', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caps',
            name='sizes',
            field=models.ManyToManyField(related_name='size', to='custom_caps.size'),
        ),
        migrations.AlterField(
            model_name='size',
            name='name',
            field=models.CharField(choices=[('Small', 'S'), ('Medium', 'M'), ('Large', 'L'), ('eXtra Large', 'XL')], max_length=30),
        ),
    ]
