# Generated by Django 4.1.4 on 2022-12-21 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_caps', models.IntegerField(verbose_name='Количество кепок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано в')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено в')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Active', 'active'), ('Passive', 'passive')], default='passive', max_length=7, verbose_name='Статус')),
                ('cost_of_delivery_caps', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость доставки кепок')),
                ('cost_of_caps', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость кепок')),
                ('fixed_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Фиксированная цена')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано в')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено в')),
                ('cart', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cart.cart')),
            ],
        ),
    ]
